spring.application.name=epidemiologia
spring.datasource.url=jdbc:postgresql://localhost:5432/epidemiologia_br
spring.datasource.username=postgres
spring.datasource.password=2899

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
